# Generated by Django 2.1.2 on 2019-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=30)),
                ('Eloc', models.CharField(max_length=30)),
                ('Eadd', models.CharField(max_length=30)),
            ],
        ),
    ]
